import { ChatUser, Message } from "./types";

export const DIRECT_MESSAGES: ChatUser[] = [
  {
    id: "1",
    name: "Anna Mann",
    status: "online",
    unreadCount: 2,
    lastMessage: "Can you review the policy document?",
    timestamp: "10:30 AM",
    avatarColor: "bg-pink-500",
  },
  {
    id: "2",
    name: "Andre Triplett",
    status: "online",
    lastMessage: "Thanks for the update!",
    timestamp: "09:15 AM",
    isPinned: true,
    avatarColor: "bg-blue-500",
  },
  {
    id: "3",
    name: "Luigi Chafloque",
    status: "away",
    lastMessage: "Meeting at 3 PM",
    timestamp: "Yesterday",
    avatarColor: "bg-green-500",
  },
  {
    id: "4",
    name: "Ivan Ballin",
    status: "online",
    unreadCount: 1,
    lastMessage: "Premium calculation sent",
    timestamp: "10:22 AM",
    avatarColor: "bg-purple-500",
  },
  {
    id: "5",
    name: "Oluvaseun Cyriloye",
    status: "offline",
    lastMessage: "Will send by EOD",
    timestamp: "Tuesday",
    avatarColor: "bg-yellow-500",
  },
  {
    id: "6",
    name: "Shira Mitzmann",
    status: "online",
    lastMessage: "Approved ✅",
    timestamp: "10:00 AM",
    isMuted: true,
    avatarColor: "bg-red-500",
  },
  {
    id: "7",
    name: "Joseph Defalco",
    status: "away",
    lastMessage: "Need your signature",
    timestamp: "Monday",
    avatarColor: "bg-indigo-500",
  },
  {
    id: "8",
    name: "Norma Titcomb",
    status: "online",
    unreadCount: 5,
    lastMessage: "Urgent: Client waiting",
    timestamp: "10:45 AM",
    isPinned: true,
    avatarColor: "bg-teal-500",
  },
  {
    id: "9",
    name: "Krystal Arthur-Vining",
    status: "offline",
    lastMessage: "Documents received",
    timestamp: "Sunday",
    avatarColor: "bg-orange-500",
  },
  {
    id: "10",
    name: "Alex Defalco",
    status: "online",
    lastMessage: "Call me when free",
    timestamp: "10:20 AM",
    avatarColor: "bg-cyan-500",
  },
  {
    id: "11",
    name: "Monika Sylvester",
    status: "away",
    lastMessage: "See attached file",
    timestamp: "Yesterday",
    avatarColor: "bg-purple-500",
  },
];



export const INITIAL_MESSAGES: Message[] = [
  {
    id: "m1",
    content: "Hey there! How's the project going?",
    senderId: "1",
    senderName: "Anna Mann",
    timestamp: "10:25 AM",
    isOwn: false,
  },
  {
    id: "m2",
    content: "Going well! Just finished the policy review.",
    senderId: "me",
    senderName: "You",
    timestamp: "10:27 AM",
    isOwn: true,
  },
  {
    id: "m3",
    content: "Great! Can you send me the updated document?",
    senderId: "1",
    senderName: "Anna Mann",
    timestamp: "10:28 AM",
    isOwn: false,
  },
  {
    id: "m4",
    content: "Sure, I'll send it in the next 30 minutes.",
    senderId: "me",
    senderName: "You",
    timestamp: "10:30 AM",
    isOwn: true,
  },
  {
    id: "m5",
    content: "Perfect, thanks!",
    senderId: "1",
    senderName: "Anna Mann",
    timestamp: "10:30 AM",
    isOwn: false,
  },
];
