import React, { useRef } from "react";
import HeroSection, { IHerosectionprops } from "./HeroSection";
import WhyToChoose from "./WhyToChoose";
import WhyToChooseUs from "./WhyToChooseUs";
import TestimonialsSection, {
  ITestimonialsSectionProps,
} from "../Products/components/SubServices/Components/TestimonialsSection";
import HomeLoanFaqs, {
  IHomeLoanFaqsprops,
} from "../Products/components/SubServices/LoansComponent/HomeLoanFaqs";
import OurServices from "./OurServices";
import HowItWorks from "./HowItWorks";
import Partners from "./Partners";
import SolarCalculator from "./SolarCalculator";
import GoogleAdSense from "@/components/GoogleAdSense";


const testimonialsData: ITestimonialsSectionProps = {
  words: [
    {
      name: "Nisha",
      desc: "The solar panels have reduced my electricity bill significantly. I am very happy with the quality and performance of the system.",
      rating: 5,
    },
    {
      name: "Trisha",
      desc: "I was impressed with the professionalism of the team. They explained everything clearly and did a great job with the installation.",
      rating: 5,
    },
    {
      name: "Charan",
      desc: "I was skeptical at first, but the solar panels have exceeded my expectations. The savings are substantial and the system looks great on my roof.",
      rating: 5,
    },
    {
      name: "Bhargav",
      desc: "The installation process was seamless and the team was very helpful. I would definitely recommend them to anyone looking to go solar.",
      rating: 5,
    },
  ],
};
const SolarFaqsdata: IHomeLoanFaqsprops = {
  heading: "Frequently Asked Questions",
  Faqs: [
    {
      id: 1,
      question: "What is the cost of solar panels?",
      answer:
        "The cost of solar panels varies depending on the size and efficiency of the system. However, the cost of solar panels has decreased significantly over the years making it more affordable for homeowners.",
    },
    {
      id: 2,
      question: "How long do solar panels last?",
      answer:
        "Solar panels typically last for 25 years or more. The lifespan of solar panels is dependent on the quality of the panels and the maintenance of the system.",
    },
    {
      id: 3,
      question: "What is the maintenance cost of solar panels?",
      answer:
        "The maintenance cost of solar panels is very low. Solar panels do not have any moving parts and do not require regular maintenance. The only maintenance required is to clean the panels occasionally to ensure maximum efficiency.",
    },
    {
      id: 4,
      question: "Do solar panels work during the night or on cloudy days?",
      answer:
        "Solar panels work only during the day when the sun is shining. They do not work during the night or on cloudy days. However, the energy generated by the solar panels during the day can be stored in batteries to power your home during the night or on cloudy days.",
    },
  ],
};

const PartnerImages = [
  {
    image: "/solar/images/partners/image1.png",
  },
  {
    image: "/solar/images/partners/image2.png",
  },
  {
    image: "/solar/images/partners/image3.png",
  },
  {
    image: "/solar/images/partners/image4.png",
  },
  {
    image: "/solar/images/partners/image5.png",
  },
  {
    image: "/solar/images/partners/image6.png",
  },
  {
    image: "/solar/images/partners/image3.png",
  },
  {
    image: "/solar/images/partners/image4.png",
  },
];
const HeroSectionData: IHerosectionprops = {
  bgimage:
    "https://cdn.pixabay.com/photo/2017/03/13/07/34/photovoltaic-2138992_640.jpg",
  heading: "Solar Energy ",
  heading2: "changing",
  subheading: " The future world",

  descriptions:
    "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.The point of using that it has a more.",
  btntext: "Learn More",
  overlaystyle: "bg-blue-600/40",
  overlaycolor: {},
};

const SolarPage = () => {
  const Ref = useRef<HTMLDivElement>(null);

  const handleScrollToDown = () => {
    if (Ref.current) {
      Ref.current.scrollIntoView({ behavior: "smooth" })
    }
  }
  return (
    <div>
      <HeroSection {...HeroSectionData} onScrollToPackages={handleScrollToDown} />
      <div className="md:mt-[0px]" ref={Ref}>
        <SolarCalculator />
      </div>

      <WhyToChoose />
      <OurServices />
      <WhyToChooseUs />
      <div className="md:px-8 px-3 mb-[45px] max-w-[98%] mx-auto md:mb-[64px] flex flex-col items-center gap-4">
        <h1 className="font-bold md:text-[24px] text-[18px] ">
          Recommended for You
        </h1>
        <GoogleAdSense />
      </div>
      <HowItWorks />
      <Partners images={PartnerImages} />
      <div className="mb-[45px] md:mb-[64px]">
        <TestimonialsSection {...testimonialsData} />
      </div>
      <HomeLoanFaqs heading={SolarFaqsdata.heading} Faqs={SolarFaqsdata.Faqs} />
    </div>
  );
};

export default SolarPage;
