export enum IndianState {
  Telangana = 'Telangana',
  AndhraPradesh = 'Andhra Pradesh',
  Karnataka = 'Karnataka',
  TamilNadu = 'Tamil Nadu',
  Maharashtra = 'Maharashtra',
  Kerala = 'Kerala',
  Gujarat = 'Gujarat',
  Delhi = 'Delhi',
  UttarPradesh = 'Uttar Pradesh',
  Rajasthan = 'Rajasthan',
  Punjab = 'Punjab',
  WestBengal = 'West Bengal',
  Bihar = 'Bihar',
  Jharkhand = 'Jharkhand',
  Odisha = 'Odisha',
  Haryana = 'Haryana',
  Chhattisgarh = 'Chhattisgarh',
  Assam = 'Assam',
  Goa = 'Goa',
  HimachalPradesh = 'Himachal Pradesh',
  Uttarakhand = 'Uttarakhand',
  Tripura = 'Tripura',
  Manipur = 'Manipur',
  Meghalaya = 'Meghalaya',
  Mizoram = 'Mizoram',
  Nagaland = 'Nagaland',
  ArunachalPradesh = 'Arunachal Pradesh',
  Sikkim = 'Sikkim',
  AndamanAndNicobarIslands = 'Andaman and Nicobar Islands',
  Chandigarh = 'Chandigarh',
  DadraAndNagarHaveliAndDamanAndDiu = 'Dadra and Nagar Haveli and Daman and Diu',
  JammuAndKashmir = 'Jammu and Kashmir',
  Ladakh = 'Ladakh',
  Lakshadweep = 'Lakshadweep',
  Puducherry = 'Puducherry',
}

export enum UserKind {
  CUSTOMER = 'CUSTOMER',
  SELLER = 'SELLER',
  STAFF = 'STAFF',
  SERVICE_PROVIDER = 'SERVICE_PROVIDER',
  AGENT = 'AGENT',
}

export enum UserRole {
  ADMIN = 'ADMIN',
  STANDARD = 'STANDARD',
}
